#!/bin/bash

# =============================================================================
# MCP Stack - Comprehensive Test Suite
# =============================================================================
#
# Runs health checks, curl integration tests, and vitest suites across the
# Annabelle MCP stack: Orchestrator, Thinker, and all HTTP/stdio MCPs.
#
# Prerequisites:
#   - Stack should be running (use ./start-all.sh)
#   - Node.js 18+ installed
#
# Usage:
#   ./test.sh           # Run all tests
#   ./test.sh --quick   # Run only health checks + quick curl tests
#   ./test.sh --vitest  # Run only vitest tests (skip curl tests)
#
# =============================================================================

set -e

# Colors
BOLD='\033[1m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

# Counters
PASSED=0
FAILED=0
SKIPPED=0
CURL_PASSED=0
CURL_FAILED=0

# MCPs directory
MCP_DIR="$(cd "$(dirname "$0")" && pwd)"

# Read auth token (generated by start-all.sh)
TOKEN_FILE="$HOME/.annabelle/annabelle.token"
if [ -f "$TOKEN_FILE" ]; then
  ANNABELLE_TOKEN=$(cat "$TOKEN_FILE")
  export ANNABELLE_TOKEN
  TOKEN_HEADER=(-H "X-Annabelle-Token: $ANNABELLE_TOKEN")
else
  ANNABELLE_TOKEN=""
  TOKEN_HEADER=()
fi

# Parse arguments
RUN_CURL=true
RUN_VITEST=true

for arg in "$@"; do
  case $arg in
    --quick)
      RUN_VITEST=false
      ;;
    --vitest)
      RUN_CURL=false
      ;;
  esac
done

# =============================================================================
# Helper Functions
# =============================================================================

print_header() {
  echo -e "\n${BOLD}${BLUE}╔═══════════════════════════════════════════════════════════════════╗${RESET}"
  echo -e "${BOLD}${BLUE}║  $1${RESET}"
  echo -e "${BOLD}${BLUE}╚═══════════════════════════════════════════════════════════════════╝${RESET}\n"
}

print_section() {
  echo -e "\n${BOLD}${CYAN}━━━ $1 ━━━${RESET}\n"
}

check_health() {
  local name=$1
  local url=$2
  local expected=$3

  echo -n "  Checking $name... "

  RESPONSE=$(curl -s --connect-timeout 5 "$url" 2>/dev/null || echo "CONNECT_FAILED")

  if [ "$RESPONSE" = "CONNECT_FAILED" ]; then
    echo -e "${YELLOW}DOWN (not running)${RESET}"
    return 1
  elif echo "$RESPONSE" | grep -q "$expected"; then
    echo -e "${GREEN}UP${RESET}"
    return 0
  else
    echo -e "${YELLOW}UNHEALTHY${RESET}"
    return 1
  fi
}

run_mcp_tests() {
  local name=$1
  local dir=$2

  if [ ! -d "$dir" ]; then
    echo -e "  ${YELLOW}⚠ $name directory not found - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  if [ ! -f "$dir/package.json" ]; then
    echo -e "  ${YELLOW}⚠ $name has no package.json - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  # Check if test script exists
  if ! grep -q '"test"' "$dir/package.json"; then
    echo -e "  ${YELLOW}⚠ $name has no test script - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  echo -e "  Running ${BOLD}$name${RESET} tests..."

  cd "$dir"

  if npm test 2>&1; then
    echo -e "  ${GREEN}✓ $name tests passed${RESET}"
    ((PASSED++)) || true
  else
    echo -e "  ${RED}✗ $name tests failed${RESET}"
    ((FAILED++)) || true
  fi

  cd "$MCP_DIR"
}

run_mcp_unit_tests() {
  local name=$1
  local dir=$2

  if [ ! -d "$dir" ]; then
    echo -e "  ${YELLOW}⚠ $name directory not found - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  if [ ! -f "$dir/package.json" ]; then
    echo -e "  ${YELLOW}⚠ $name has no package.json - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  # Check if test:unit script exists
  if ! grep -q '"test:unit"' "$dir/package.json"; then
    echo -e "  ${YELLOW}⚠ $name has no test:unit script - skipping${RESET}"
    ((SKIPPED++)) || true
    return
  fi

  echo -e "  Running ${BOLD}$name${RESET} unit tests..."

  cd "$dir"

  if npm run test:unit 2>&1; then
    echo -e "  ${GREEN}✓ $name unit tests passed${RESET}"
    ((PASSED++)) || true
  else
    echo -e "  ${RED}✗ $name unit tests failed${RESET}"
    ((FAILED++)) || true
  fi

  cd "$MCP_DIR"
}

test_curl() {
  local name=$1
  local url=$2
  local data=$3
  local expected=$4

  echo -n "  $name... "

  RESPONSE=$(curl -s -X POST "$url" \
    -H "Content-Type: application/json" \
    "${TOKEN_HEADER[@]}" \
    -d "$data" 2>/dev/null || echo "FAILED")

  if echo "$RESPONSE" | grep -q "$expected"; then
    echo -e "${GREEN}✓${RESET}"
    ((CURL_PASSED++)) || true
  else
    echo -e "${RED}✗${RESET}"
    ((CURL_FAILED++)) || true
  fi
}

test_curl_get() {
  local name=$1
  local url=$2
  local expected=$3

  echo -n "  $name... "

  RESPONSE=$(curl -s "${TOKEN_HEADER[@]}" "$url" 2>/dev/null || echo "FAILED")

  if echo "$RESPONSE" | grep -q "$expected"; then
    echo -e "${GREEN}✓${RESET}"
    ((CURL_PASSED++)) || true
  else
    echo -e "${RED}✗${RESET}"
    ((CURL_FAILED++)) || true
  fi
}

# =============================================================================
# Main Test Suite
# =============================================================================

print_header "MCP Stack - Comprehensive Test Suite"

echo -e "Test mode: ${BOLD}$([ "$RUN_CURL" = true ] && [ "$RUN_VITEST" = true ] && echo "Full" || ([ "$RUN_VITEST" = true ] && echo "Vitest only" || echo "Quick (curl only)"))${RESET}"
echo -e "MCP Directory: ${CYAN}$MCP_DIR${RESET}"

# =============================================================================
# Section 1: Health Checks
# =============================================================================

print_section "Section 1: Health Checks"

# HTTP services (only Orchestrator and Thinker have HTTP ports; MCPs are all stdio)
ORCHESTRATOR_UP=false
THINKER_UP=false

echo -e "  ${BOLD}HTTP Service Health Checks:${RESET}"
check_health "Orchestrator (8010)" "http://localhost:8010/health" "ok" && ORCHESTRATOR_UP=true
check_health "Thinker (8006)" "http://localhost:8006/health" "ok" && THINKER_UP=true

# =============================================================================
# Section 2: Quick Curl Tests (if --quick or full mode)
# =============================================================================

if [ "$RUN_CURL" = true ]; then
  print_section "Section 2: Quick Integration Tests (curl)"

  # =====================================================
  # Orchestrator: routes to all downstream MCPs
  # =====================================================
  if [ "$ORCHESTRATOR_UP" = true ]; then
    echo -e "\n  ${BOLD}Orchestrator (routes to all MCPs):${RESET}"
    test_curl "Get status" "http://localhost:8010/tools/call" \
      '{"name": "get_status", "arguments": {}}' "ready"
    test_curl_get "List tools" "http://localhost:8010/tools/list" "name"
    test_curl "List chats (via Telegram)" "http://localhost:8010/tools/call" \
      '{"name": "telegram_list_chats", "arguments": {"limit": 5}}' "success"
    test_curl "Get memory stats (via Memory)" "http://localhost:8010/tools/call" \
      '{"name": "memory_get_memory_stats", "arguments": {}}' "success"
    test_curl "Get workspace info (via Filer)" "http://localhost:8010/tools/call" \
      '{"name": "filer_get_workspace_info", "arguments": {}}' "success"
  fi

  # Thinker tests (if running)
  if [ "$THINKER_UP" = true ]; then
    echo -e "\n  ${BOLD}Thinker:${RESET}"
    # Thinker doesn't expose tools, just health
    THINKER_RESP=$(curl -s http://localhost:8006/health 2>/dev/null)
    if echo "$THINKER_RESP" | grep -q "llmProvider"; then
      echo -e "  Thinker config... ${GREEN}✓${RESET}"
      ((CURL_PASSED++)) || true
    else
      echo -e "  Thinker config... ${RED}✗${RESET}"
      ((CURL_FAILED++)) || true
    fi
  fi

  echo -e "\n  Curl tests: ${GREEN}$CURL_PASSED passed${RESET}, ${RED}$CURL_FAILED failed${RESET}"
fi

# =============================================================================
# Section 3: Vitest Tests (if --vitest or full mode)
# =============================================================================

if [ "$RUN_VITEST" = true ]; then
  # =====================================================
  # Section 3: Unit Tests (no running server required)
  # =====================================================
  # Stdio MCPs (Memorizer, Guardian, 1Password) are spawned by
  # Orchestrator — they don't have standalone HTTP ports. Only unit
  # tests (InMemoryTransport) run here. Integration coverage comes
  # from Orchestrator tests in Section 5.
  print_section "Section 3: Unit Tests (per-MCP)"

  run_mcp_unit_tests "Memorizer" "$MCP_DIR/Memorizer-MCP"
  run_mcp_unit_tests "Gmail" "$MCP_DIR/Gmail-MCP"
  run_mcp_unit_tests "Guardian" "$MCP_DIR/Guardian"
  run_mcp_tests "CodeExec" "$MCP_DIR/CodeExec-MCP"

  # =====================================================
  # Section 4: Standalone HTTP MCP Tests
  # =====================================================
  # MCPs that run their own HTTP servers — full integration test
  # suites run against their standalone ports.
  print_section "Section 4: HTTP MCP Tests (standalone servers)"

  run_mcp_tests "Filer" "$MCP_DIR/Filer-MCP"
  run_mcp_tests "Telegram" "$MCP_DIR/Telegram-MCP"
  run_mcp_tests "Searcher" "$MCP_DIR/Searcher-MCP"

  # =====================================================
  # Section 5: Orchestrator Integration Tests
  # =====================================================
  # Routes through Orchestrator (8010) to all downstream MCPs.
  # Covers tool routing, workflows, jobs, and lifecycle tests.
  print_section "Section 5: Orchestrator Integration Tests"
  run_mcp_tests "Orchestrator" "$MCP_DIR/Orchestrator"

  # =====================================================
  # Section 6: Thinker Tests
  # =====================================================
  print_section "Section 6: Thinker Tests"
  run_mcp_tests "Thinker" "$MCP_DIR/Thinker"
fi

# =============================================================================
# Summary
# =============================================================================

print_header "Test Summary"

TOTAL=$((PASSED + FAILED + SKIPPED))

echo -e "  ${BOLD}Vitest Suites:${RESET}"
echo -e "    ${GREEN}Passed:${RESET}  $PASSED"
echo -e "    ${RED}Failed:${RESET}  $FAILED"
echo -e "    ${YELLOW}Skipped:${RESET} $SKIPPED"
echo ""

if [ "$RUN_CURL" = true ]; then
  echo -e "  ${BOLD}Curl Tests:${RESET}"
  echo -e "    ${GREEN}Passed:${RESET}  $CURL_PASSED"
  echo -e "    ${RED}Failed:${RESET}  $CURL_FAILED"
  echo ""
fi

if [ $FAILED -eq 0 ] && [ ${CURL_FAILED:-0} -eq 0 ]; then
  echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════════════════════${RESET}"
  echo -e "${BOLD}${GREEN}  ✓ ALL TESTS PASSED${RESET}"
  echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════════════════════${RESET}"
  exit 0
else
  echo -e "${BOLD}${RED}═══════════════════════════════════════════════════════════════════${RESET}"
  echo -e "${BOLD}${RED}  ✗ SOME TESTS FAILED${RESET}"
  echo -e "${BOLD}${RED}═══════════════════════════════════════════════════════════════════${RESET}"
  exit 1
fi
